### PR TITLE
Add support for Linux Mint 19.2 Tina (via Ubuntu 18.04 LTS)

### PR DESCRIPTION
**Pull request by clefebvre**
This commit adds support for Linux Mint 19.2 Tina.

It also adds LMDE 3 Cindy and Linux Mint 19.1 Tessa to the list of
supported releases in README.md. These were supported in the setup scripts
already but weren't mentioned in the readme.

### CODE REVIEW

**Comment by clefebvre** [comment]
While working on this PR, I noticed a couple of supported releases were now obsolete.

For instance, the following releases reached End Of Life:

- LMDE 2 Betsy
- Ubuntu 14.04 trusty and all its derivatives (qiana, rafaela, rebecca, rosa..)
- Ubuntu precise (really ancient) and its derivatives.. Linux Mint Maya.. 

I didn't remove them in this PR as it wasn't part of its scope and I wasn't sure if you wanted to keep them in.

**Comment by SkoZombie** [comment]
This would be great to merge as I just ran into issues with installing NodeJS 12.x using the provided instructions on Tina

**Comment by message** [comment]
Why it's not merged since July?

**Comment by mathielo** [comment]
Any reason for this to be hanging? Seems like it's been ready to be merged for a while now. Would be great to have this available!

**Comment by danger89** [comment]
MERGE

**Comment by danger89** [comment]
Solved by me: https://node.melroy.org/

**Comment by clefebvre** [comment]
Codename for 19.3 is going to be "tricia". Feel free to add it to the list already.

Same for LMDE 4... "debbie".

**Comment by danger89** [comment]
> Codename for 19.3 is going to be "tricia" (based on 18.04). Feel free to add it to the list already.
> 
> Same for LMDE 4... "debbie" (based on Debian buster).

Thanks, fixed! htttps://node.melroy.org is now ready for the future (future proof).

**Comment by Perlover** [comment]
+1
Dear developers! Please merge this PR! It's very important for Linux Mint users!

**Comment by danger89** [comment]
@Perlover in the main while try: https://node.melroy.org/

**Comment by Perlover** [comment]
> @Perlover in the main while try: https://node.melroy.org/

I know about your site but i want to add official nodejs repository. As i right understand are you not official developer of nodejs?

**Comment by danger89** [comment]
> > @Perlover in the main while try: https://node.melroy.org/
> 
> I know about your site but i want to add official nodejs repository. As i right understand are you not official developer of nodejs?

That may be true, but NodeSource are also not 'official' developers of nodejs, in fact they are a company. I'm just an open source developer, doing tons of different projects and contributions.

**Comment by igsu** [comment]
@clefebvre this was resolved as of #972, it updates all scripts for Node.js installations, even Node.js 13, which was released after your PR. We appreciate that you took the time to deal with this issue.

Thank you very much for your active collaboration!

**Comment by clefebvre** [comment]
thanks @igsu, 19.3 was released as BETA today (stable before Xmas), can you add it as well? Its codename is "tricia".

PS: In README.md, you're missing 19.1 Tessa and Tina is 19.2, not 19.

**Comment by igsu** [comment]
Thanks @clefebvre, good catch! I already updated it.
About Tricia: once there is a stable version, I will take care of it.

**Pull request closed without merging**
