### PR TITLE
Add support for Ubilinux dolcetto

### PR DESCRIPTION
**Pull request by gutobrz**
Ubilinux dolcetto is compatible with Debian stretch. 
Already installed and test with success.

### CODE REVIEW

**Comment by danger89** [comment]
Solved by me: https://node.melroy.org/

**Comment by bcomnes** [comment]
good to know @danger89.  Is everything still good with this repo here?

**Comment by danger89** [comment]
This is ambiguous. This official repo (not mine) didn't merge the change yet..

**Comment by igsu** [comment]
Thanks for your collaboration @gutobrz!

**Pull request merged**
