### PR TITLE
Added tina for node setup_12.x

### PR DESCRIPTION
**Pull request by dipto0321**

### CODE REVIEW

**Comment by mathielo** [comment]
Why not add support for all Node.js versions at once? I would suggest adding for all versions, same as it was done in #766.

**Comment by dipto0321** [comment]
Awesome!

**Comment by danger89** [comment]
Fixed by me: https://node.melroy.org/

**Comment by igsu** [comment]
@dipto0321 this was resolved as of #972, it updates all scripts for Node.js installations, which was omitted in your Pull Request.

Thank you very much for your active collaboration!

**Pull request closed without merging**
