### PR TITLE
Add Linux Mint Tina support

### PR DESCRIPTION
**Pull request by mathe27**

### CODE REVIEW

**Comment by zkelo** [comment]
How soon this pull request will be merged?

**Comment by deanpress** [comment]
Need this too

**Comment by danger89** [comment]
Try: https://node.melroy.org/

**Comment by zkelo** [comment]
> Try: https://node.melroy.org/

Thanks. But it bothers me that there the 10th version of Node is listed as LTS, although the current LTS version is 12 on the official website

**Comment by danger89** [comment]
Noted, I will change that ASAP.

**Comment by danger89** [comment]
> why is necessary to be so specific?
> Couldn't it be something more generic like: ubuntu-based distros?

No idea.., since even the packages files for apt Debian based systems are equal across the distros:

- https://deb.nodesource.com/node_13.x/dists/buster/main/binary-amd64/Packages
- https://deb.nodesource.com/node_13.x/dists/xenial/main/binary-amd64/Packages
- https://deb.nodesource.com/node_13.x/dists/trusty/main/binary-amd64/Packages
- https://deb.nodesource.com/node_13.x/dists/jessie/main/binary-amd64/Packages

Thanks for the hint, I will take this improvement idea along during my [full mirror creation](https://node.melroy.org).

**Comment by SrStick** [comment]
> > why is necessary to be so specific?
> > Couldn't it be something more generic like: ubuntu-based distros?
> 
> No idea.., since even the packages files for apt Debian based systems are equal across the distros:
> 
>     * https://deb.nodesource.com/node_13.x/dists/buster/main/binary-amd64/Packages
> 
>     * https://deb.nodesource.com/node_13.x/dists/xenial/main/binary-amd64/Packages
> 
>     * https://deb.nodesource.com/node_13.x/dists/trusty/main/binary-amd64/Packages
> 
>     * https://deb.nodesource.com/node_13.x/dists/jessie/main/binary-amd64/Packages
> 
> 
> Thanks for the hint, I will take this improvement idea along during my [full mirror creation](https://node.melroy.org).
> 
> ps. You properbly mean `debian-based` instead of `ubuntu-based`, since Ubuntu is even based on Debian. Debian is Independent champagne !

Have you considered creating a snap or flatpak version?

**Comment by igsu** [comment]
@mathe27 this was resolved as of #972, it updates all scripts for Node.js installations, which was omitted in your PR.
Thank you very much for your collaboration!

**Pull request closed without merging**
