### PR TITLE
Support deepin 15.11+

### PR DESCRIPTION
**Pull request by ldsink**
deepin 15.11 released on July 19. 
[DEEPIN 15.11 - BETTER NEVER STOPS](https://www.deepin.org/en/2019/07/19/deepin15-11/)

**deepin unstable version is officially not supported since deepin 15.11. For unstable version users, please download stable version here and install it as soon as possible.**

deepin v15.11 based on debian 9.0 (stretch) and codename changed from `panda` to `lion`, version changed from `unstable` to `stable`.

### CODE REVIEW

**Comment by danger89** [comment]
Solved by me: https://node.melroy.org/

**Comment by ldsink** [comment]
@edsadr

**Comment by officialpiyush** [comment]
Waiting for it to get merged :)

**Comment by officialpiyush** [comment]
Any updates for this PR?

**Pull request closed without merging**
