### PR TITLE
Include Kali Linux 2.0

### PR DESCRIPTION
**Pull request by mattbrun**
Include Kali Linux 2.0 distro as a Debian Jessie derivate

### CODE REVIEW

**Comment by wblankenship** [comment]
Hey @mattbrun,

It appears that you already submitted this PR: https://github.com/nodesource/distributions/pull/119

**Comment by mattbrun** [comment]
@wblankenship yes indeed.
I submitted it for the `_setup.sh` file, but it seems the production of `setup_4.x` has not considered my previous patch...

**Comment by wblankenship** [comment]
Ah I see.

This looks good to me. Researched the change on the last PR and everything checks out.

Thanks for your contributions :smile:

**Comment by mattbrun** [comment]
Thanks to you for the good work! :smile:

**Pull request merged**
