### PR TITLE
Add support for LinuxMint 18 (Sarah)

### PR DESCRIPTION
**Pull request by gperdomor**
Add support for LinuxMint 18 (Sarah)

### CODE REVIEW

**Comment by rvagg** [comment]
@chrislea what think you about this? I said in #313 that we wouldn't be supporting it until it's out of Beta, _but_, we're not building for it, we're just aliasing so perhaps it's not a big deal to add this early. Xenial is stable and we support it already and Sarah is based on Xenial.

**Comment by chrislea** [comment]
@rvagg LGTM, I don't see any issues with the Mint beta. The "beta" state we want to avoid is unsupported base state from the vendor. But as long as the distro in question is based on a distro we already do support, no problem adding it.

**Comment by retrohacker** [comment]
@rvagg this looks good to me as well. I share @chrislea's opinion on beta's.

**Comment by rvagg** [comment]
OK, thanks @retrohacker & @chrislea, I've added this in 57188ae and pushed live. Please give it a try @gperdomor and let us know if you have any trouble with it.

**Comment by BandonRandon** [comment]
Worked for me! I originally used LinuxBrew but it had an outdated version so glad to be able to do this via the package manager.

**Pull request closed without merging**
