### PR TITLE
add ci

### PR DESCRIPTION
**Pull request by gengjiawen**
Pipeline: https://circleci.com/workflow-run/a54bfd03-62f5-4327-b0a7-3ccd333c843a.

image

### CODE REVIEW

**Comment by gengjiawen** [comment]
@chrislea @rvagg Can you review this ? Thanks.

**Comment by rvagg** [comment]
@gkrizek who owns this repo these days? Someone @ NS should probably look at this. Also https://github.com/nodesource/distributions/pull/758 needs addressing which will add flow-on here if this is accepted.
If this repo has been dropped on the floor since Chris & I left perhaps you could add look at adding permissions so that I can push changes to setup* files to S3 or wherever they point to these days. Ping me privately if you want to discuss.

**Comment by gkrizek** [comment]
Hey @rvagg,

Sorry for the late reply. I was on Paternity Leave the last several weeks. This repository is handled by our Support team now, but stuff like this I'll probably take a look at. I've made a note to come back to this as soon as I can. (a lot to catch up on).

**Comment by rvagg** [comment]
paternity leave! congrats! I hope you're surviving. Getting the gpg one merged was the critical bit, thanks for doing that

**Comment by gengjiawen** [comment]
New ci: https://circleci.com/workflow-run/c3587a5d-5ee7-447b-a934-2ff77ce5b967
Also add fedora:
image

**Comment by gkrizek** [comment]
https://circleci.com/gh/nodesource/workflows/distributions

Thanks for the PR @gengjiawen !

**Pull request merged**
