### PR TITLE
Update setup_12.x to support Fedora 34

### PR DESCRIPTION
**Pull request by Triplelexx**
I think this is all that is required. I only needed this version. If approved I could do the others, or close this.

### CODE REVIEW

**Comment by dcrdev** [comment]
The fedora-release package provides redhat-release in it's spec:
```
https://src.fedoraproject.org/rpms/fedora-release/blob/f34/f/fedora-release.spec#_372
```

It also creates a symlink between redhat-release and fedora-release:
```
https://src.fedoraproject.org/rpms/fedora-release/blob/f34/f/fedora-release.spec#_747
```

There's a hardcoded version number somewhere - will take a look.

**Comment by dcrdev** [comment]
Relevant:
https://src.fedoraproject.org/rpms/fedora-release/pull-request/183

**Comment by jdavidavendano** [comment]
Hi, we have detected this issue and we are currently working to solve it.

**Comment by igsu** [comment]
As of #1230 Fedora 34 support has been added. Thanks for your help on this @Triplelexx.

**Pull request closed without merging**
