### PR TITLE
Alias stretch to jessie in all scripts.

### PR DESCRIPTION
**Pull request by hjc1710**
Looks like there's a sid repo, but not a stretch one. Right now the script just breaks on stretch, and looks like it works fine using Jessie.

### CODE REVIEW

**Comment by rvagg** [comment]
It's been our policy to not officially support unreleased distro versions, but perhaps Debian testing is a special case because of the ridiculously long timespans and the active use. I'll ask @chrislea and @wblankenship (a stretch user I believe) for opinions here.

Of course you can always just manually put in the repo, the instructions are now listed on the README and you can s/jessie/stretch/.

**Comment by hjc1710** [comment]
Ahhh, I can understand that. That can quickly lead to a wormhole of issues that aren't super productive to solve, while also not affecting too many users.

Although, I do agree that if anything is going to be a special exception to this rule, it would be Debian testing. Debian in general is the 3rd most popular Linux distro, and testing seems to be a fairly popular release in the Debian eco-system.

As a small note, `lsb_release -r -s` will give you `testing` back when run on Debian testing, couple that with `lsb_release -i -s` (which returns `Debian`), and we might be able to integrate that into the generic Debian fallback block like so:

```sh
if [ "X${DISTRO}" == "Xdebian" ]; then
  print_status "Unknown Debian-based distribution, checking /etc/debian_version..."
  NEWDISTRO=$([[ -e /etc/debian_version ]] && cat /etc/debian_version  | cut -d/ -f1)
  ## NEW
  if ["X${NEWDISTRO}" == "X"]; then
    # alias Debian Testing to latest Debian (currently 8.0 [Jessie])
    NEWDISTRO=$([[ $(lsb_release -r -s) -eq 'testing']] && echo 'jessie')
  fi
  ## END NEW
  if [ "X${DISTRO}" == "X" ]; then
    print_status "Could not determine distribution from /etc/debian_version..."
  else
    DISTRO=$NEWDISTRO
    print_status "Found \"${DISTRO}\" in /etc/debian_version..."
  fi
fi
```

Obviously, tweak to your hearts content, but you should get the idea.

Looking at this, I also think there's a bug in the script, shouldn't:

```sj
if [ "X${DISTRO}" == "X" ]; then
```

Be:

```sh
if [ "X${NEWDISTRO}" == "X" ]; then
```

Otherwise, the check we did for `NEWDISTRO` is totally useless. Or am I missing something?

Anyways, this is far from a fix I need, I integrated this into my system already, I just thought it would be nice if you guys supported Debian Testing out of the box (especially since you've gone out of  your way to have specific builds for each release instead of just masking them all under `sid` or `vivid`), so I whipped this together. 

Curiosity question though, why did you guys choose to not use Launchpad and to make your own script instead?

**Comment by chrislea** [comment]
Just chiming in here @rvagg -- I actually do think it makes sense to try and support Debian testing at any given point. A **lot** of people use testing on production systems. Yes, generally those people also know how to install packages from repos that don't exactly match, but we should be trying to make this as easy as possible. Debian testing is not like Ubuntu where there's a standard release schedule that you can track a release against. It's more like "this is everything that we think is currently stable, but we aren't ready to cut a full new release just yet", and it generally is multiple years between actual releases.

Also, to answer @hjc1710 we don't use Launchpad anymore because it only targets Ubuntu (not Debian). So you can't build a package for say Jessie on Launchpad.

**Comment by hjc1710** [comment]
To put what @chrislea said about years in between releases into perspective, check out the Debian [release history](https://en.wikipedia.org/wiki/Debian#Release_timeline). It's generally 2+ years in between any sort of release, **at all**. When you compare that to Ubuntu's 6 month release schedule, supporting Debian testing, but not whatever pre-release Ubuntu is currently targeting, starts to make a lot of sense.

Debian testing is also a joy to use on desktops, in addition to any use for production servers. You get the nice stability and sanity of Debian, plus a rolling release so your packages are nice and fresh :smile:. So, I highly support and applaud the decision to make an exception for Debian testing, and to support it, even though it's not an official release. :+1: 

If you use my second suggestion (altering the Debian fallback check), then maintaining Debian testing for the future forward should be super easy. When a new stable Debian rolls out (and thusly, a new testing), you can just go in and change `jessie` to `stretch`, which has to be done for LMDE anyway, but keep the checks around determining if we're running Debian testing in place and unchanged. If you guys want to use that alteration to the script, let me know, I can easily open another PR after testing on my machine (but that has to wait for later tonight since EFI is being a bitch right now).

I figured you weren't using Launchpad due to it being too Ubuntu-centric (also, since you're packaging RPM's, it seems like you'd want a more universal system that just doesn't even bother with Launchpad), but I was just curious! Launchpad and `add-apt-repository` are really, really nice... for Ubuntu users, so I completely understand not wanting to maintain this on Launchpad **and** somewhere else, just so you can give a real release to anyone not on Ubuntu.

I really applaud this entire effort to make the node release schedule more rolling, and more official. Also, as a Debian user, I really applaud giving me an alternative to Launchpad, as I really hate having to add Launchpad sources into my apt, because it generally ends in me "lying" and having to use the `vivid` release, which is far from ideal. Having an official, Debian-specific release is great! Awesome job guys!

:clap: :tada: :clap: :tada:

**Comment by wblankenship** [comment]
I think everything that needs to be said about Debian Testing has already been said here, but I do want to throw in my :+1: to supporting it.

**Comment by rvagg** [comment]
So, the question is then, do we build specifically for testing (in which case do we need to rebuild all prior debs regularly to match what the debian testing stack is as it shifts?) or is aliasing to jessie enough? See #106 for the alias option, I can deploy that pretty quick and it should work but there's no guarantees that it's not going to cause package conflicts later on. Please comment there @wblankenship and @chrislea.

**Comment by chrislea** [comment]
I think that for now just aliasing should be fine. The number of dependencies node / iojs have is really, really small since we compile basically everything in statically. I think the only thing that might clearly throw a monkey wrench in things is a major change to `libstdc++` or some major shift in the compiler toolchain. And if either of those happen, then there's going to be a general disturbance in the force all over for testing and we'll just react to it then as needed.

$0.02.

**Comment by hjc1710** [comment]
Poking through issues, this (and #106) would solve #94, just to make sure that doesn't get missed.

Thanks for the speedy merge guys, just close this when you're content with the other PR :smile:!

**Comment by rvagg** [comment]
I've updated the scripts and tested it in testing and it's good to go. I'll have to update the README too but that will take some careful wording ..

**Comment by wblankenship** [comment]
:+1: to aliasing until something breaks and then revisiting this.

**Comment by deployable** [comment]
Just a note that [Debian stretch is now frozen](https://lists.debian.org/debian-devel-announce/2017/02/msg00001.html) for release so should be only getting serious bug fixes from now. The release could be in the next few months.

**Pull request closed without merging**
